name: recipe_web
description: My Recipes flutter app ported to Angular Dart.
version: 2.0.3
author: ppolasek <ppolasek@users.noreply.github.com>

environment:
  sdk: '>=1.24.2 <2.0.0'

dependencies:
  angular2: "^3.0.0"
#  angular_components: "^0.5.1"
  logging: "^0.11.3+1"
  bootstrap: "^3.3.7"

dev_dependencies:
  angular_test: ^1.0.0-beta+2
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  test: ^0.12.21

transformers:
- angular2:
    entry_points:
    - web/main.dart
    - test/**_test.dart
    resolved_identifiers:
        BrowserClient: 'package:http/browser_client.dart'
        Client: 'package:http/http.dart'
- angular2/transform/reflection_remover:
    $include: test/**_test.dart
- test/pub_serve:
    $include: test/**_test.dart
- dart_to_js_script_rewriter
- bootstrap:
    url: //maxcdn.bootstrapcdn.com/bootstrap/{{version}}
    version: 3.3.7
